name: inkstep
description: With you every step of the way

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_analytics: ^4.0.2
  firebase_messaging: ^5.1.2
  cloud_firestore: ^0.12.8
  firebase_auth: ^0.14.0+2
  flutter_swiper: ^1.1.6 # Latest
  multi_image_picker: ^4.5.3 # Latest
  auto_size_text: ^2.0.0 # Latest
  bloc: ^0.14.1 # Latest
  flutter_bloc: ^0.15.0 # Latest
  get_it: ^1.0.3 # Latest 1.0.3+1
  equatable: ^0.2.5 # Latest
  http: ^0.12.0 # Latest 0.12.0+2
  palette_generator: ^0.2.0 # Latest
  intl: ^0.15.8 #Â Latest
  flutter_staggered_grid_view: ^0.2.7 # Latest
  shared_preferences: ^0.5.3
  speech_bubble: ^0.0.1
  flutter_spinkit: ^3.1.0 # Latest
  firebase_storage: ^3.0.6
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/inkstep.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/offline/
